### ISSUE TITLE
Input_number.set_value range 0 to 5 instead of 0 to 7 for main fan

### ISSUE THREAD

**Issue by RonandoDeLaVega** [marcopal74/home-assistant-palazzetti#10]
Hello marcopal74,

First of all, thanks a lot for your really nice work ! 👍 

I've got a Palazzetti Julie 3 stove and I can change the value of the main fan from 0 to 7 :

  - 0 : no fan
  - 1 to 5 : from 1 to 5 fan power
  - 6 : High power fan
  - 7 : Auto power fan

When I try to submit "auto", I'v got this issue :
![image](https://user-images.githubusercontent.com/32481592/156754679-3cfa9338-057d-44db-b7ba-f407b6f82eb7.png)

When I submit "auto" in my Palazzetti app :
![image](https://user-images.githubusercontent.com/32481592/156755667-106fc6a8-7bb1-47bc-b149-3804cd79fa72.png)

Can you have a look please ?

Thanks,
Ronando

**Comment by marcopal74** [comment]
Hello Ronando, the level 6 and 7 cannot be assigned directly via the Fan input_number. There is a specific API to do that.
If you **update the integration** a few days ago I've **added the AUTO switch** button that calls that specific API.
You can now use the automation to toggle that switch instead of setting the value of 7 to the Fan input_number.

**Comment by RonandoDeLaVega** [comment]
Hello marcopal74, 

Ah nice, thanks a lot !
