### ISSUE TITLE
Bad string and temperature precision

### ISSUE THREAD

**Issue by array81** [marcopal74/home-assistant-palazzetti#16]
Hi,

I have 2 small problems:

1. On sensors I have this string "kTemperaturaAcquaRitorno". The label is not correct moreever I think is the the "Temp. Mandata" and not "Temp. Ritorno" because I just have other "Temp. Ritorno" with low value;
2. Sometimes both "kTemperaturaAcquaRitorno" and "Temp. Ritorno" have 8 digits after the comma;

Thanks

**Comment by marcopal74** [comment]
Hello @array81, 

Point 1 -  can you tell me which model of stove/boiler you have? I've a boiler and the labels are OK but the label of the sensor depends also on the configuration. (Attribute CONFIG of the Product).
I couldn't test all the models so there can uncovered situations.
<img width="540" alt="Screenshot 2023-02-03 alle 02 09 53" src="https://user-images.githubusercontent.com/28279074/216487209-097324de-8255-4d93-8cba-c19da6944b16.png">
Anyway you can change the name of the label from the HomeAssistant UI 😉

Point 2 - in the integration I don't manipulate the data received from the CBox, it means that if there are 8 digits it's because that's what it comes from the CBox. You can solve this issue by creating a template sensor over the sensor of the integration in your configuration.yaml file:

```- platform: template
  sensors:
    t_mandata:
      friendly_name: 'T. Mandata'
      value_template: '{{ states.sensor.temp_mandata.state | round(1,default=none) }}'
      unit_of_measurement: "°C"
      device_class: temperature
```

**Comment by array81** [comment]
Thanks for fast reply.
About point1 I have a Palazzetti Ermione Idro 26kW. I cannot find "Attribute CONFIG of the Product" on Home Assistant.
I changed the name on HA but can I change also ID entity ot it's a problem?

**Comment by marcopal74** [comment]
CONFIG is an attribute of the sensor which name is "sensor.<your_product_name>" the one with the Fireplace icon. Can you find it?

**Comment by array81** [comment]
Hi,
I not have config but I think the problem is that I use WirelessPalaControl to connect the stove. I can find only these:

![image](https://user-images.githubusercontent.com/9898768/216594453-04a4da2c-43a5-476b-a240-2565b0603181.png)

**Comment by marcopal74** [comment]
Sorry @array81 I'm really burnt out!!! please check the attributes of the bynary_sensor.product. My mistake, really sorry...

**Comment by array81** [comment]
The config value us 1.

The WirelessPalaControll works very well.
I have only a small problema with ON/OFF switch, when it changes state for a few minutes it becomes unavailable on HA but it is not a hardware or connection problem.  I've read that others have similar problems.

**Comment by array81** [comment]
Othet questione.
Is there a way to monitor the status of the circulator (pump) of the water?  to know if it is on or off

**Comment by marcopal74** [comment]
> The config value is 1.

In config 1 the main temp sensor is the water outgoing from the stove to the heating system (TemperaturaAcquaMandata) that is T1
while the coming back to the stove water is T2 (TemperaturaAcquaRitorno) 
the set point is done on water temperature
<img width="829" alt="config_1" src="https://user-images.githubusercontent.com/28279074/216850878-b8852e8c-fd12-49f2-8bf2-d2a0c2a314ed.png">

> The WirelessPalaControll works very well. I have only a small problema with ON/OFF switch, when it changes state for a few minutes it becomes unavailable on HA but it is not a hardware or connection problem. I've read that others have similar problems.

The unavailability of the ON/OFF switch is due to the fact that the integration (as the App) cannot control the ON/OFF during the intermediate steps between the ON switch and the BURNING state as well as the intermediate phases between BURNING and the OFF state when you switch OFF. During those phases the stove changes automatically state and the interaction is not allowed 👍🏻.
